trigger:
  branches:
    exclude:
      - "*"
pr:
  branches:
    include:
      - "*"

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install bandit
      pip install safety
      pip install detect-secrets
      pip install trivy
    displayName: 'Install security tools'

  - script: |
      bandit -r . -f html -o bandit_report.html
    displayName: 'Run Bandit SAST'

  - script: |
      safety check --full-report > safety_report.txt
    displayName: 'Run Safety Dependency Check'

  - script: |
      detect-secrets scan > secrets_baseline.json
      detect-secrets audit --report secrets_baseline.json > secrets_report.html
    displayName: 'Run Detect-Secrets'

  - script: |
      trivy fs --format html -o trivy_report.html .
    displayName: 'Run Trivy Container Scan'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)'
      ArtifactName: 'SecurityReports'
      publishLocation: 'Container'
    displayName: 'Publish Security Reports'
